import { PageCategory } from './types';

export const progression: PageCategory[] = [
  {
    title: 'West Limegrave',
    subtitle: 'Level: 1~10 Upgrades: 0 ~ +1',
    tasks: [
      'obtain-wetstone-knife',
      'limegrave-west-map-fragment',
      'boc-seamster-quest',
      'find-sellen',
      'talk-to-roderika',
      'find-ashes-of-war-merchant',
      'meet-potboy',
      'talk-to-d-hunter',
      'murkwater-cave',
    ],
  },
  {
    title: 'East Limegrave',
    subtitle: 'Level: 5~10 Upgrades: +1 ~ +2',
    tasks: [
      'talk-to-kenneth',
      'get-wondrous',
      'limegrave-east-map-fragment',
      'get-flask-materials-from-erdtree',
      'activate-siofra-river-well',
      'trigger-blaidd',
      'liberate-fort-haight',
      'get-reward-kenneth-haight',
      'complete-summonwater',
      'talk-to-d-hunter-at-roundtable',
      'teleport-bestial-sanctum',
    ],
  },
  {
    title: 'Southern Limegrave & Weeping Peninsula',
    subtitle: 'Level: 20 Upgrades: 3+',
    tasks: [
      'meet-yura',
      'kill-dragon-agheel',
      'obtain-royal-house-scroll',
      'default-knights-cavalry',
      'obtain-memory-slot-1',
      'get-sacred-tears-1',
      'get-flask-materials-erdtree-1',
      'complete-castle-morne',
    ],
  },
  {
    title: 'Roundtable Hold',
    tasks: [
      'defeat-margit',
      'visit-roundtable-hold',
      'talk-roundtable-npcs',
      'upgrade-weapons-1',
    ],
  },
  {
    title: 'Stormveil Castle',
    subtitle: 'Level: 30~40 Upgrades: +3 ~ +4',
    tasks: [
      'stormveil-alternate-entrance',
      'defeat-banished-knight',
      'obtain-the-stonesword-key',
      'dispel-fog-enter-gates',
      'locate-nepheli-loux',
      'clear-the-castle-1',
      'prepare-for-boss-summon-nepheli',
      'restore-godricks-great-rune',
    ],
  },
  {
    title: 'Liurnia of the Lakes South',
    subtitle: 'Level: 40~50 Upgrades: +3 ~ +4',
    tasks: [
      'talk-to-boc-the-seamster',
      'meet-sorcerer-thops',
      'obtain-academy-scroll',
      'obtain-fire-monks-prayerbook',
      'get-liurnia-map-fragments',
      'get-cookbooks-and-ritual-pot',
      'meet-patches-get-flask-upgrades',
      'visit-rose-church',
      'complete-malefactors-evergoal',
      'loot-sacrificial-twig',
      'obtain-raya-lucaria-academy-key',
    ],
  },
  {
    title: 'Liurnia of the Lakes South',
    subtitle: 'Level: 40~50 Upgrades: +3 ~ +4',
    tasks: [
      'talk-to-boc-the-seamster',
      'meet-sorcerer-thops',
      'obtain-academy-scroll',
      'obtain-fire-monks-prayerbook',
      'get-liurnia-map-fragments',
      'get-cookbooks-and-ritual-pot',
      'meet-patches-get-flask-upgrades',
      'visit-rose-church',
      'complete-malefactors-evergoal',
      'loot-sacrificial-twig',
      'obtain-raya-lucaria-academy-key',
    ],
  },
  {
    title: 'Raya Lucaria Academy',
    subtitle: 'Level: 50~60 Upgrades: +4 ~ +6',
    tasks: [
      'acquire-academy-glintstone-key',
      'obtain-gravity-well-sorcery',
      'get-carian-knight-set',
      'get-conspectus-scroll',
      'get-olivinus-glintstone-crown-and-ritual-pot',
      'defeat-red-wolf-of-radagon',
      'access-secret-radagon-upstairs-area',
      'get-key-golden-seed-glintstone-crown',
      'expore-upper-rooftops',
      'get-imbued-sword-key',
      'defeat-moongrum-carian-knight',
      'deal-with-iron-ball',
      'defeat-rennala',
    ],
  },
];
