import { PageCategory } from './types';

export const progression: PageCategory[] = [
  {
    title: 'West Limegrave',
    subtitle: 'Level: 1~10 Upgrades: 0 ~ +1',
    tasks: [
      'obtain-wetstone-knife',
      'limegrave-west-map-fragment',
      'boc-seamster-quest',
      'find-sellen',
      'talk-to-roderika',
      'find-ashes-of-war-merchant',
      'meet-potboy',
      'talk-to-d-hunter',
      'murkwater-cave',
    ],
  },
  {
    title: 'East Limegrave',
    subtitle: 'Level: 5~10 Upgrades: +1 ~ +2',
    tasks: [
      'talk-to-kenneth',
      'get-wondrous',
      'limegrave-east-map-fragment',
      'get-flask-materials-from-erdtree',
      'activate-siofra-river-well',
      'trigger-blaidd',
      'liberate-fort-haight',
      'get-reward-kenneth-haight',
      'complete-summonwater',
      'talk-to-d-hunter-at-roundtable',
      'teleport-bestial-sanctum',
    ],
  },
  {
    title: 'Southern Limegrave & Weeping Peninsula',
    subtitle: 'Level: 20 Upgrades: 3+',
    tasks: [
      'meet-yura',
      'kill-dragon-agheel',
      'obtain-royal-house-scroll',
      'default-knights-cavalry',
      'obtain-memory-slot-1',
      'get-sacred-tears-1',
      'get-flask-materials-erdtree-1',
      'complete-castle-morne',
    ],
  },
  {
    title: 'Roundtable Hold',
    tasks: [
      'defeat-margit',
      'visit-roundtable-hold',
      'talk-roundtable-npcs',
      'upgrade-weapons-1',
    ],
  },
  {
    title: 'Stormveil Castle',
    subtitle: 'Level: 30~40 Upgrades: +3 ~ +4',
    tasks: [
      'stormveil-alternate-entrance',
      'defeat-banished-knight',
      'obtain-the-stonesword-key',
      'dispel-fog-enter-gates',
      'locate-nepheli-loux',
      'clear-the-castle-1',
      'prepare-for-boss-summon-nepheli',
      'restore-godricks-great-rune',
    ],
  },
  {
    title: 'Liurnia of the Lakes South',
    subtitle: 'Level: 40~50 Upgrades: +3 ~ +4',
    tasks: [
      'talk-to-boc-the-seamster',
      'meet-sorcerer-thops',
      'obtain-academy-scroll',
      'obtain-fire-monks-prayerbook',
      'get-liurnia-map-fragments',
      'get-cookbooks-and-ritual-pot',
      'meet-patches-get-flask-upgrades',
      'visit-rose-church',
      'complete-malefactors-evergoal',
      'loot-sacrificial-twig',
      'obtain-raya-lucaria-academy-key',
    ],
  },
  {
    title: 'Nokstella, Eternal City & Lake of Rot',
    subtitle: 'Level: 80+ Upgrades: +15 ~ +20 (Lake of Rot)',
    tasks: [
      'enter-ainsel-river-main',
      'collect-miniature-ranni',
      'enter-nokstella-eternal-city',
      'collect-key-items-and-spirit-ashes-nokstella',
      'talk-to-miniature-ranni',
      'enter-lake-of-rot',
      'obtain-map-fragment-nokstella',
      'use-the-discarded-palace-key',
      'defeat-dragonkin-soldier',
      'enter-grand-cloister-nokstella',
      'defeat-astel-naturalborn-of-the-void',
    ],
  },
  {
    title: 'Altus Plateau',
    subtitle: 'Level: 60+ Upgrades: +10 ~ +14',
    tasks: [
      'get-access-to-altus-plateau',
      'complete-western-altus-objectives',
      'talk-to-millicent',
      'complete-old-altus-tunnel',
      'complete-shaded-castle',
      'talk-to-millicent-again',
      'complete-golden-lineage-evergaolboc-the-seamster',
      'obtain-zone-map-talk-to-boc-and-corhyn',
      'complete-secong-church-of-marika',
      'get-minord-erdtree-flask-upgrade-complete-valley-objectives',
      'complete-dominula-and-talk-to-millicent',
      'explore-eastern-altus-heights',
      'meet-goldmask-report-to-corhyb',
      'unlock-mt-gelmir-site-of-grace',
    ],
  },
  {
    title: 'Mt Gelmir',
    subtitle: 'Level: 80+ Upgrades: +15 ~ +20',
    tasks: [
      'defeat-tibia-mariner',
      'complete-wyndham-ruins-and-catacombs',
    ],
  },
  {
    title: 'Leyndell, Royal Capital',
    tasks: [
      'defeat-draconic-tree-sentinel',
      'enter-leyndell',
      'go-to-the-erdtree-sanctuary',
      'defeat-godfrey-first-elden-lord-golden-shade',
      'get-in-the-queens-bedchamber',
      'defeat-morgott-the-omen-king',
      'barrier-in-capital-outskirts-is-no-longer',
      'proceed-to-the-forbidden-lands',
    ],
  },
  {
    title: 'Forbidden Lands',
    tasks: [
      'enter-leyndell-royal-capital',
      'defeat-black-blade-kindred',
      'proceed-to-mountaintops-of-giants',
    ],
  },
];
